In [1]:
# Dependencies
from bs4 import BeautifulSoup
import requests

import pandas as pd

In [2]:
# $50M+
url = 'https://www.boxofficemojo.com/alltime/weekends/?pagenum=m50&sort=opengross&p=.htm&order=DESC'

In [3]:
tables = pd.read_html(url)

#Tables is a list of all the tables on the page, the required dataframe is stored in index 3
df = tables[3]

df.columns = ['Rank', 'Title', 'Studio', 'Opening', '% of Total', 'Theaters', 'Average', 'Total Gross', 'Date']

#Clean up title that's an extra row
df = df.iloc[1:]

df.set_index('Rank', inplace=True)

df.head()

,Title,Studio,Opening,% of Total,Theaters,Average,Total Gross,Date
Rank,,,,,,,,
1,Avengers: Endgame,BV,"$357,115,007",41.6%,4662,"$76,601","$858,373,000",4/26/2019
2,Avengers: Infinity War,BV,"$257,698,183",38.0%,4474,"$57,599","$678,815,482",4/27/2018
3,Star Wars: The Force Awakens,BV,"$247,966,675",26.5%,4134,"$59,982","$936,662,225",12/18/2015
4,Star Wars: The Last Jedi,BV,"$220,009,584",35.5%,4232,"$51,987","$620,181,382",12/15/2017
5,Jurassic World,Uni.,"$208,806,270",32.0%,4274,"$48,855","$652,270,625",6/12/2015

In [4]:
# Tab -  $40 - 50M, has the remaining data
url2 = 'https://www.boxofficemojo.com/alltime/weekends/?pagenum=m4050&sort=opengross&p=.htm&order=DESC'

tables2 = pd.read_html(url2)

#Tables is a list of all the tables on the page, the required dataframe is stored in index 3
df2 = tables2[3]

df2.columns = ['Rank', 'Title', 'Studio', 'Opening', '% of Total', 'Theaters', 'Average', 'Total Gross', 'Date']

#Clean up title that's an extra row
df2 = df2.iloc[1:]

df2.set_index('Rank', inplace=True)

#Replace abbreviated studio names with actual Studio names
#print(df['Studio'].unique())

#df2['Studio'].replace(['BV', 'Uni.', 'WB', 'LGF' ,'Sony', 'Sum.' ,'LG/S', 'Fox' ,'Par.', 'WB (NL)', 'P/DW' ,'DW', 'NM' ,'NL', 'MGM'], ['Buena Vista', 'Universal', 'Warner Bros.', 'Lionsgate' ,'Sony / Columbia', 'Summit Entertainment' ,'Lionsgate' , '20th Century Fox' ,'Paramount', 'Warner Bros.', 'Paramount' ,'Dreamworks SKG', 'Newmarket' ,'New Line', 'MGM'], inplace=True)


df2.head()

,Title,Studio,Opening,% of Total,Theaters,Average,Total Gross,Date
Rank,,,,,,,,
249,Taken 2,Fox,"$49,514,769",35.4%,3661,"$13,525","$139,854,287",10/5/2012
250,How to Train Your Dragon 2,Fox,"$49,451,322",27.9%,4253,"$11,627","$177,002,924",6/13/2014
251,Rush Hour 3,NL,"$49,100,158",35.0%,3778,"$12,996","$140,125,968",8/10/2007
252,Wreck-It Ralph,BV,"$49,038,712",25.9%,3752,"$13,070","$189,422,889",11/2/2012
253,Neighbors,Uni.,"$49,033,915",32.7%,3279,"$14,954","$150,157,400",5/9/2014

In [5]:

boxOffice_df = pd.concat([df,df2])
boxOffice_df = boxOffice_df.iloc[0:250]
boxOffice_df.head()

,Title,Studio,Opening,% of Total,Theaters,Average,Total Gross,Date
Rank,,,,,,,,
1,Avengers: Endgame,BV,"$357,115,007",41.6%,4662,"$76,601","$858,373,000",4/26/2019
2,Avengers: Infinity War,BV,"$257,698,183",38.0%,4474,"$57,599","$678,815,482",4/27/2018
3,Star Wars: The Force Awakens,BV,"$247,966,675",26.5%,4134,"$59,982","$936,662,225",12/18/2015
4,Star Wars: The Last Jedi,BV,"$220,009,584",35.5%,4232,"$51,987","$620,181,382",12/15/2017
5,Jurassic World,Uni.,"$208,806,270",32.0%,4274,"$48,855","$652,270,625",6/12/2015

In [6]:
#Replace abbreviated studio names with actual Studio names
print(boxOffice_df['Studio'].unique())

boxOffice_df['Studio'].replace(['BV', 'Uni.', 'WB', 'LGF' ,'Sony', 'Sum.' ,'LG/S', 'Fox' ,'Par.', 'WB (NL)', 'P/DW' ,'DW', 'NM' ,'NL', 'MGM'], ['Buena Vista', 'Universal', 'Warner Bros.', 'Lionsgate' ,'Sony / Columbia', 'Summit Entertainment' ,'Lionsgate' , '20th Century Fox' ,'Paramount', 'Warner Bros.', 'Paramount' ,'Dreamworks SKG', 'Newmarket' ,'New Line', 'MGM'], inplace=True)

['BV' 'Uni.' 'WB' 'LGF' 'Sony' 'Sum.' 'LG/S' 'Fox' 'Par.' 'WB (NL)' 'P/DW'
 'DW' 'NM' 'NL' 'MGM']

In [7]:
boxOffice_df.head()

,Title,Studio,Opening,% of Total,Theaters,Average,Total Gross,Date
Rank,,,,,,,,
1,Avengers: Endgame,Buena Vista,"$357,115,007",41.6%,4662,"$76,601","$858,373,000",4/26/2019
2,Avengers: Infinity War,Buena Vista,"$257,698,183",38.0%,4474,"$57,599","$678,815,482",4/27/2018
3,Star Wars: The Force Awakens,Buena Vista,"$247,966,675",26.5%,4134,"$59,982","$936,662,225",12/18/2015
4,Star Wars: The Last Jedi,Buena Vista,"$220,009,584",35.5%,4232,"$51,987","$620,181,382",12/15/2017
5,Jurassic World,Universal,"$208,806,270",32.0%,4274,"$48,855","$652,270,625",6/12/2015

In [8]:
boxOffice_df['Title']

Rank
1                                Avengers: Endgame
2                           Avengers: Infinity War
3                     Star Wars: The Force Awakens
4                         Star Wars: The Last Jedi
5                                   Jurassic World
6                            Marvel's The Avengers
7                                    Black Panther
8                             The Lion King (2019)
9                          Avengers: Age of Ultron
10                                   Incredibles 2
11                      Captain America: Civil War
12                     Beauty and the Beast (2017)
13                                      Iron Man 3
14     Harry Potter and the Deathly Hallows Part 2
15              Batman v Superman: Dawn of Justice
16                           The Dark Knight Rises
17                                 The Dark Knight
18                 The Hunger Games: Catching Fire
19                    Rogue One: A Star Wars Story
20                                  Captain Marvel
21                                The Hunger Games
22                                    Spider-Man 3
23                  Jurassic World: Fallen Kingdom
24                                       Furious 7
25                  Guardians of the Galaxy Vol. 2
26                     The Twilight Saga: New Moon
27         The Twilight Saga: Breaking Dawn Part 2
28         The Twilight Saga: Breaking Dawn Part 1
29      Pirates of the Caribbean: Dead Man's Chest
30                                    Finding Dory
                          ...
221                                  The Wolverine
222                          The LEGO Batman Movie
223                                 Batman Forever
224                          Paranormal Activity 3
225                               Superman Returns
226                           The Bourne Supremacy
227                The Divergent Series: Insurgent
228                                       I, Robot
229                                Men in Black II
230                                    Home (2015)
231                                    Van Helsing
232                                         8 Mile
233                                   Men in Black
234                              Bohemian Rhapsody
235                                     Prometheus
236                                         Wanted
237                                           Coco
238                              Jurassic Park III
239                                    The Village
240                                        Dunkirk
241                               2 Fast 2 Furious
242                                    Jackass 3-D
243                               Mr. & Mrs. Smith
244                               Independence Day
245                                  A Quiet Place
246                                  The Boss Baby
247                                      King Kong
248                        The Great Gatsby (2013)
249                                        Taken 2
250                     How to Train Your Dragon 2
Name: Title, Length: 250, dtype: object

In [9]:
# Dependencies
import requests
# API URL
url = "http://www.omdbapi.com/?apikey=57e34fb6&plot=full&t="

In [10]:
movie_data = []
for title in boxOffice_df['Title']:
    if "(" in title:
        year = title[-5:][:-1]
        title = title[:-6]
        movie = requests.get(url + title + '&y=' + year).json()
        if movie['Response'] == "True":
            movie_data.append(movie)
    else:
        movie = requests.get(url + title).json()
        if movie['Response'] == "True":
            movie_data.append(movie)

missing_movies = ['The Avengers','The Lorax','Monsters vs. Aliens','Insurgent','Jackass 3D','The Grinch']

for title in missing_movies:
    movie = requests.get(url + title).json()
    movie_data.append(movie)

In [11]:
actors = []
genre = []
plot= []
imdb = []
rotten_tomatoes = []
metacritic = []
    
for movie in movie_data:
    actors.append(movie['Actors'])
    genre.append(movie['Genre'])
    plot.append(movie['Plot'])
    for rating in movie['Ratings']:
        imdb.append(rating['Value'])
        rotten_tomatoes.append(rating['Value'])
        metacritic.append(rating['Value'])

In [13]:
pd.DataFrame(movie_data)

,Actors,Awards,BoxOffice,Country,DVD,Director,Genre,Language,Metascore,Plot,...,Response,Runtime,Title,Type,Website,Writer,Year,imdbID,imdbRating,imdbVotes
0,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",N/A,N/A,"USA, UK, Canada",30 Jul 2019,"Anthony Russo, Joe Russo","Action, Adventure, Sci-Fi","English, Japanese, Xhosa",78,After the devastating events of Avengers: Infi...,...,True,181 min,Avengers: Endgame,movie,N/A,"Christopher Markus (screenplay by), Stephen Mc...",2019,tt4154796,8.6,"561,813"
1,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...",N/A,"$664,987,816",USA,14 Aug 2018,"Anthony Russo, Joe Russo","Action, Adventure, Sci-Fi",English,68,The Avengers and their allies must be willing ...,...,True,149 min,Avengers: Infinity War,movie,http://marvel.com/movies/movie/223/avengers_in...,"Christopher Markus (screenplay by), Stephen Mc...",2018,tt4154756,8.5,"706,537"
2,"J.J. Abrams, John Boyega, Anthony Carboni, Gwe...",N/A,N/A,USA,N/A,N/A,N/A,English,N/A,N/A,...,True,N/A,Star Wars: The Force Awakens World Premiere Re...,movie,N/A,Scott Bromley,2015,tt7768640,6.7,7
3,"Mark Hamill, Carrie Fisher, Adam Driver, Daisy...",Nominated for 4 Oscars. Another 12 wins & 71 n...,"$619,117,636",USA,27 Mar 2018,Rian Johnson,"Action, Adventure, Fantasy, Sci-Fi",English,85,Rey develops her newly discovered abilities wi...,...,True,152 min,Star Wars: The Last Jedi,movie,http://www.starwars.com/the-last-jedi/,"Rian Johnson, George Lucas (based on character...",2017,tt2527336,7.1,"472,141"
4,"Chris Pratt, Bryce Dallas Howard, Irrfan Khan,...",14 wins & 57 nominations.,"$528,757,749",USA,20 Oct 2015,Colin Trevorrow,"Action, Adventure, Sci-Fi",English,59,22 years after the original Jurassic Park fail...,...,True,124 min,Jurassic World,movie,http://www.jurassicworldmovie.com/,"Rick Jaffa (screenplay by), Amanda Silver (scr...",2015,tt0369610,7.0,"544,726"
5,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",14 nominations.,"$501,105,037",USA,15 May 2018,Ryan Coogler,"Action, Adventure, Sci-Fi","English, Swahili, Nama, Xhosa, Korean",88,After the events of Captain America: Civil War...,...,True,134 min,Black Panther,movie,https://www.marvel.com/movies/black-panther,"Ryan Coogler, Joe Robert Cole, Stan Lee (based...",2018,tt1825683,7.3,"538,936"
6,"Chiwetel Ejiofor, John Oliver, James Earl Jone...",N/A,N/A,USA,N/A,Jon Favreau,"Animation, Adventure, Drama, Family, Musical",English,55,"After the murder of his father, a young lion p...",...,True,118 min,The Lion King,movie,https://movies.disney.com/the-lion-king-2019,"Jeff Nathanson (screenplay by), Brenda Chapman...",2019,tt6105098,7.1,"102,621"
7,"Robert Downey Jr., Chris Hemsworth, Mark Ruffa...",7 wins & 45 nominations.,"$429,113,729",USA,02 Oct 2015,Joss Whedon,"Action, Adventure, Sci-Fi","English, Korean",66,Tony Stark creates the Ultron Program to prote...,...,True,141 min,Avengers: Age of Ultron,movie,http://marvel.com/avengers,"Joss Whedon, Stan Lee (based on the Marvel com...",2015,tt2395427,7.3,"680,834"
8,"Craig T. Nelson, Holly Hunter, Sarah Vowell, H...",N/A,N/A,USA,23 Oct 2018,Brad Bird,"Animation, Action, Adventure, Comedy, Family, ...",English,80,The Incredibles hero family takes on a new mis...,...,True,118 min,Incredibles 2,movie,http://movies.disney.com/the-incredibles-2,Brad Bird,2018,tt3606756,7.7,"215,257"
9,"Chris Evans, Robert Downey Jr., Scarlett Johan...",16 wins & 65 nominations.,"$408,080,554",USA,13 Sep 2016,"Anthony Russo, Joe Russo","Action, Adventure, Sci-Fi","English, German, Xhosa, Russian, Romanian, Hindi",75,With many people fearing the actions of super ...,...,True,147 min,Captain America: Civil War,movie,http://marvel.com/captainamerica#/home,"Christopher Markus (screenplay by), Stephen Mc...",2016,tt3498820,7.8,"602,106"
10,"Emma Watson, Dan Stevens, Luke Evans, Josh Gad",Nominated for 2 Oscars. Another 12 wins & 65 n...,"$503,974,884",USA,06 Jun 2017,Bill Condon,"Family, Fantasy, Musical, Romance",English,65,"Disney's animated classic takes on a new form,...",...,True,129 min,Beauty and the Beast,movie,http://movies.disney.com/beauty-and-the-beast-...,"Stephen Chbosky (screenplay by), Evan Spilioto...",2017,tt2771200,7.2,"243,966"
11,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...",Nominated for 1 Oscar. Another 17 wins & 61 no...,"$408,992,272",USA,24 Sep 2013,Shane Black,"Action, Adventure, Sci-Fi",English,62,"Marvel's ""Iron Man 3"" pits brash-but-brilliant...",...,True,130 min,Iron Man 3,movie,http://IronManMovie3.com,"Drew Pearce (screenplay by), Shane Black (scre...",2013,tt1300854,7.2,"703,559"
12,"Ralph Fiennes, Michael Gambon, Alan Rickman, D...",Nominated for 3 Oscars. Another 45 wins & 91 n...,"$381,000,185","USA, UK",11 Nov 2011,David Yates,"Adventure, Drama, Fantasy, Mystery",English,87,"Harry, Ron, and Hermione continue their quest ...",...,True,130 min,Harry Potter and the Deathly Hallows: Part 2,movie,http://www.HarryPotter.com/,"Steve Kloves (screenplay), J.K. Rowling (novel)",2011,tt1201607,8.1,"700,975"
13,"Ben Affleck, Henry Cavill, Amy Adams, Jesse Ei...",14 wins & 30 nominations.,"$293,792,936",USA,19 Jul 2016,Zack Snyder,"Action, Adventure, Sci-Fi",English,44,The general public is concerned over having Su...,...,True,151 min,Batman v Superman: Dawn of Justice,movie,http://www.facebook.com/batmanvsuperman,"Chris Terrio, David S. Goyer, Bob Kane (Batman...",2016,tt2975590,6.5,"585,766"
14,"Christian Bale, Gary Oldman, Tom Hardy, Joseph...",Nominated for 1 BAFTA Film Award. Another 38 w...,"$448,130,642","UK, USA",03 Dec 2012,Christopher Nolan,"Action, Thriller","English, Arabic",78,Despite his tarnished reputation after the eve...,...,True,164 min,The Dark Knight Rises,movie,http://www.thedarkknightrises.com/,"Jonathan Nolan (screenplay), Christopher Nolan...",2012,tt1345836,8.4,"1,408,657"
15,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",Won 2 Oscars. Another 152 wins & 155 nominations.,"$533,316,061","USA, UK",09 Dec 2008,Christopher Nolan,"Action, Crime, Drama, Thriller","English, Mandarin",84,Set within a year after the events of Batman B...,...,True,152 min,The Dark Knight,movie,http://thedarkknight.warnerbros.com/,"Jonathan Nolan (screenplay), Christopher Nolan...",2008,tt0468569,9.0,"2,101,295"
16,"Jennifer Lawrence, Liam Hemsworth, Jack Quaid,...",Nominated for 1 Golden Globe. Another 22 wins ...,"$336,663,349",USA,07 Mar 2014,Francis Lawrence,"Action, Adventure, Sci-Fi, Thriller",English,76,Twelve months after winning the 74th Hunger Ga...,...,True,146 min,The Hunger Games: Catching Fire,movie,http://www.thehungergamesexplorer.com/us/,"Simon Beaufoy (screenplay), Michael Arndt (scr...",2013,tt1951264,7.5,"581,625"
17,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",Nominated for 2 Oscars. Another 23 wins & 78 n...,"$532,171,696",USA,04 Apr 2017,Gareth Edwards,"Action, Adventure, Sci-Fi",English,65,All looks lost for the Rebellion against the E...,...,True,133 min,Rogue One: A Star Wars Story,movie,http://www.starwars.com/,"Chris Weitz (screenplay by), Tony Gilroy (scre...",2016,tt3748528,7.8,"489,309"
18,"Brie Larson, Samuel L. Jackson, Ben Mendelsohn...",N/A,N/A,"USA, Australia",11 Jun 2019,"Anna Boden, Ryan Fleck","Action, Adventure, Sci-Fi",English,64,Carol Danvers becomes one of the universe's mo...,...,True,123 min,Captain Marvel,movie,https://movies.disney.com/captain-marvel,"Anna Boden (screenplay by), Ryan Fleck (screen...",2019,tt4154664,7.0,"359,923"
19,"Stanley Tucci, Wes Bentley, Jennifer Lawrence,...",Nominated for 1 Golden Globe. Another 33 wins ...,"$407,981,652",USA,18 Aug 2012,Gary Ross,"Action, Adventure, Sci-Fi, Thriller",English,68,"In a dystopian future, the totalitarian nation...",...,True,142 min,The Hunger Games,movie,http://thehungergamesmovie.com,"Gary Ross (screenplay), Suzanne Collins (scree...",2012,tt1392170,7.2,"803,048"
20,"Tobey Maguire, Kirsten Dunst, James Franco, Th...",Nominated for 1 BAFTA Film Award. Another 3 wi...,"$336,530,303",USA,30 Oct 2007,Sam Raimi,"Action, Adventure","English, French",59,Peter Parker has finally managed to piece toge...,...,True,139 min,Spider-Man 3,movie,http://www.sonypictures.com/movies/spiderman3/...,"Sam Raimi (screenplay), Ivan Raimi (screenplay...",2007,tt0413300,6.2,"467,228"
21,"Chris Pratt, Bryce Dallas Howard, Rafe Spall, ...",N/A,N/A,USA,18 Sep 2018,J.A. Bayona,"Action, Adventure, Sci-Fi","English, Russian",51,When the island's dormant volcano begins roari...,...,True,128 min,Jurassic World: Fallen Kingdom,movie,http://www.jurassicworld.com,"Derek Connolly, Colin Trevorrow, Michael Crich...",2018,tt4881806,6.2,"229,305"
22,"Vin Diesel, Paul Walker, Jason Statham, Michel...",Nominated for 1 Golden Globe. Another 28 wins ...,"$316,986,481","USA, China, Japan, Canada, United Arab Emirates",15 Sep 2015,James Wan,"Action, Adventure, Thriller","English, Thai, Arabic, Spanish",67,Dominic and his crew thought they'd left the c...,...,True,137 min,Furious 7,movie,http://www.furious7.com/,"Chris Morgan, Gary Scott Thompson (characters)",2015,tt2820852,7.2,"338,987"
23,"Chris Pratt, Zoe Saldana, Dave Bautista, Vin D...",Nominated for 1 Oscar. Another 12 wins & 42 no...,"$389,804,217",USA,22 Aug 2017,James Gunn,"Action, Adventure, Comedy, Sci-Fi",English,67,"After saving Xandar from Ronan's wrath, the Gu...",...,True,136 min,Guardians of the Galaxy Vol. 2,movie,https://marvel.com/guardians,"James Gunn, Dan Abnett (based on the Marvel co...",2017,tt3896198,7.6,"502,562"
24,"Kristen Stewart, Christina Jastrzembska, Rober...",20 wins & 24 nominations.,"$296,593,070",USA,20 Mar 2010,Chris Weitz,"Adventure, Drama, Fantasy, Mystery, Romance","English, Italian",44,After Bella recovers from the vampire attack t...,...,True,130 min,The Twilight Saga: New Moon,movie,http://www.newmoonthemovie.com/,"Melissa Rosenberg (screenplay), Stephenie Meye...",2009,tt1259571,4.7,"250,739"
25,"Kristen Stewart, Robert Pattinson, Taylor Laut...",21 wins & 14 nominations.,"$292,298,923",USA,02 Mar 2013,Bill Condon,"Adventure, Drama, Fantasy, Romance",English,52,The final Twilight Saga begins with Bella now ...,...,True,115 min,The Twilight Saga: Breaking Dawn - Part 2,movie,http://www.breakingdawn-themovie.com/,"Melissa Rosenberg (screenplay), Stephenie Meye...",2012,tt1673434,5.5,"217,050"
26,"Taylor Lautner, Gil Birmingham, Billy Burke, S...",11 wins & 22 nominations.,"$281,267,663",USA,11 Feb 2012,Bill Condon,"Action, Adventure, Drama, Fantasy, Romance, Th...","English, Portuguese",45,"After Bella and Edward's honeymoon, things tak...",...,True,117 min,The Twilight Saga: Breaking Dawn - Part 1,movie,http://www.breakingdawn-themovie.com/,"Melissa Rosenberg (screenplay), Stephenie Meye...",2011,tt1324999,4.9,"210,292"
27,"Johnny Depp, Orlando Bloom, Keira Knightley, J...",Won 1 Oscar. Another 42 wins & 53 nominations.,"$423,032,628",USA,05 Dec 2006,Gore Verbinski,"Action, Adventure, Fantasy","English, Turkish, Greek, Mandarin, French",53,Once again we're plunged into the world of swo...,...,True,151 min,Pirates of the Caribbean: Dead Man's Chest,movie,http://pirates.movies.com,"Ted Elliott, Terry Rossio, Ted Elliott (charac...",2006,tt0383574,7.3,"620,022"
28,"Ellen DeGeneres, Albert Brooks, Ed O'Neill, Ka...",Nominated for 1 BAFTA Film Award. Another 15 w...,"$486,292,984",USA,15 Nov 2016,"Andrew Stanton, Angus MacLane(co-director)","Animation, Adventure, Comedy, Family","English, Indonesian",77,"Dory is a wide-eyed, blue tang fish who suffer...",...,True,97 min,Finding Dory,movie,http://movies.disney.com/finding-dory,"Andrew Stanton (original story by), Andrew Sta...",2016,tt2277860,7.3,"218,175"
29,"Will Smith, Jaime FitzSimons, Ike Barinholtz, ...",Won 1 Oscar. Another 16 wins & 37 nominations.,"$325,021,779",USA,13 Dec 2016,David Ayer,"Action, Adventure, Fantasy, Sci-Fi","English, Japanese, Spanish",40,It feels good to be bad...Assemble a team of t...,...,True,123 min,Suicide Squad,movie,http://www.suicidesquad.com/,David Ayer,2016,tt1386697,6.0,"543,236"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,"Brandon Routh, Kate Bosworth, Kevin Spacey, Ja...",Nominated for 1 Oscar. Another 12 wins & 40 no...,"$200,100,000",USA,28 Nov 2006,Bryan Singer,"Action, Adventure, Sci-Fi","English, German, French",72,Following a mysterious absence of several year...,...,True,154 min,Superman Returns,movie,http://www.supermanreturns.com/,"Michael Dougherty (screenplay), Dan Harris (sc...",2006,tt0348150,6.0,"261,532"
220,"Matt Damon, Franka Potente, Brian Cox, Julia S...",5 wins & 21 nominations.,"$176,049,130","USA, Germany",07 Dec 2004,Paul Greengrass,"Action, Mystery, Thriller","English, Russian, German, Italian",73,After escaping from the emotional and physical...,...,True,108 min,The Bourne Supremacy,movie,http://www.thebournesupremacy.com/,"Robert Ludlum (novel), Tony Gilroy (screenplay)",2004,tt0372183,7.7,"410,791"
221,"Will Smith, Bridget Moynahan, Alan Tudyk, Jame...",Nominated for 1 Oscar. Another 1 win & 13 nomi...,N/A,"USA, Germany",01 Dec 1998,Alex Proyas,"Action, Crime, Drama, Mystery, Sci-Fi, Thriller",English,59,"In 2035, technophobic homicide detective Del S...",...,True,115 min,"I, Robot",movie,N/A,"Jeff Vintar (screenplay), Akiva Goldsman (scre...",2004,tt0343818,7.1,"468,911"
222,"Tommy Lee Jones, Will Smith, Rip Torn, Lara Fl...",4 wins & 15 nominations.,"$190,400,000",USA,26 Nov 2002,Barry Sonnenfeld,"Action, Adventure, Comedy, Mystery, Sci-Fi",English,49,"Kay and Jay reunite to provide our best, last ...",...,True,88 min,Men in Black II,movie,http://www.sonypictures.com/movies/meninblack/,"Lowell Cunningham (comic book ""Malibu Comics"")...",2002,tt0120912,6.2,"320,383"
223,"Jim Parsons, Rihanna, Steve Martin, Jennifer L...",2 wins & 9 nominations.,"$157,801,252",USA,28 Jul 2015,Tim Johnson,"Animation, Adventure, Comedy, Family, Fantasy,...","English, French",55,"When Oh, a loveable misfit from another planet...",...,True,94 min,Home,movie,http://www.meettheboov.com/,"Tom J. Astle (screenplay by), Matt Ember (scre...",2015,tt2224026,6.6,"86,768"
224,"Hugh Jackman, Kate Beckinsale, Richard Roxburg...",3 wins & 20 nominations.,N/A,"USA, Czech Republic, Romania",20 Sep 2005,Stephen Sommers,"Action, Adventure, Fantasy","English, Latin",35,"Van Helsing is in the world to rid all evil, e...",...,True,131 min,Van Helsing,movie,N/A,Stephen Sommers,2004,tt0338526,6.1,"231,664"
225,"Eminem, Kim Basinger, Mekhi Phifer, Brittany M...",Won 1 Oscar. Another 14 wins & 21 nominations.,"$116,638,030","USA, Germany",18 Mar 2003,Curtis Hanson,"Drama, Music",English,77,This is the inspiring captivating story of the...,...,True,110 min,8 Mile,movie,http://www.8-mile.com/,Scott Silver,2002,tt0298203,7.1,"231,355"
226,"Tommy Lee Jones, Will Smith, Linda Fiorentino,...",Won 1 Oscar. Another 19 wins & 39 nominations.,N/A,USA,23 Oct 1997,Barry Sonnenfeld,"Action, Adventure, Comedy, Sci-Fi","English, Spanish",71,Based off of the comic book. Unbeknownst to ot...,...,True,98 min,Men in Black,movie,N/A,"Lowell Cunningham (comic), Ed Solomon (screen ...",1997,tt0119654,7.3,"483,765"
227,"Rami Malek, Lucy Boynton, Gwilym Lee, Ben Hardy",N/A,N/A,"UK, USA",12 Feb 2019,Bryan Singer,"Biography, Drama, Music",English,49,The story of the legendary British rock band Q...,...,True,134 min,Bohemian Rhapsody,movie,http://www.bohemianrhapsody.com,"Anthony McCarten (story by), Peter Morgan (sto...",2018,tt1727824,8.0,"376,574"
228,"Noomi Rapace, Michael Fassbender, Charlize The...",Nominated for 1 Oscar. Another 6 wins & 46 nom...,"$126,464,904","USA, UK",09 Oct 2012,Ridley Scott,"Adventure, Mystery, Sci-Fi","English, Scottish Gaelic",64,This film is set in 2093 and takes place in th...,...,True,124 min,Prometheus,movie,http://www.prometheus-movie.com/,"Jon Spaihts, Damon Lindelof, Dan O'Bannon (bas...",2012,tt1446714,7.0,"543,126"
229,"James McAvoy, Morgan Freeman, Angelina Jolie, ...",Nominated for 2 Oscars. Another 4 wins & 20 no...,"$134,294,280","USA, Germany",02 Dec 2008,Timur Bekmambetov,"Action, Crime, Fantasy, Thriller",English,64,A young man finds out his long lost father is ...,...,True,110 min,Wanted,movie,http://www.wantedmovie.com/,"Michael Brandt (screenplay), Derek Haas (scree...",2008,tt0493464,6.7,"343,350"
230,"Anthony Gonzalez, Gael García Bernal, Benjamin...",Won 2 Oscars. Another 86 wins & 28 nominations.,"$208,487,719",USA,27 Feb 2018,"Lee Unkrich, Adrian Molina(co-director)","Animation, Adventure, Family, Fantasy, Music, ...","English, Spanish",81,Despite his family's baffling generations-old ...,...,True,105 min,Coco,movie,http://movies.disney.com/coco,"Lee Unkrich (original story by), Jason Katz (o...",2017,tt2380307,8.4,"292,392"
231,"Sam Neill, William H. Macy, Téa Leoni, Alessan...",5 wins & 15 nominations.,N/A,USA,11 Dec 2001,Joe Johnston,"Action, Adventure, Sci-Fi, Thriller","English, Spanish",42,Dr. Alan Grant is now a happy man with the pre...,...,True,92 min,Jurassic Park III,movie,http://www.jurassicpark.com,"Michael Crichton (characters), Peter Buchman, ...",2001,tt0163025,5.9,"277,610"
232,"Bryce Dallas Howard, Joaquin Phoenix, Adrien B...",Nominated for 1 Oscar. Another 4 wins & 21 nom...,"$114,170,863",USA,11 Jan 2005,M. Night Shyamalan,"Drama, Mystery, Thriller",English,44,M Night Shyamalan's The Villiage revolves arou...,...,True,108 min,The Village,movie,http://thevillage.movies.go.com/main.html,M. Night Shyamalan,2004,tt0368447,6.5,"229,667"
233,"Fionn Whitehead, Damien Bonnard, Aneurin Barna...",Won 3 Oscars. Another 51 wins & 197 nominations.,"$188,042,171","UK, Netherlands, France, USA",19 Dec 2017,Christopher Nolan,"Action, Drama, History, Thriller, War","English, French, German",94,"Evacuation of Allied soldiers from Belgium, th...",...,True,106 min,Dunkirk,movie,http://www.dunkirkmovie.com,Christopher Nolan,2017,tt5013056,7.9,"478,576"
234,"Paul Walker, Tyrese Gibson, Eva Mendes, Cole H...",4 wins & 13 nominations.,"$127,083,765","USA, Germany",30 Sep 2003,John Singleton,"Action, Crime, Thriller","English, Spanish",38,EX LAPD cop Brian O'Conner (Paul Walker) teams...,...,True,107 min,2 Fast 2 Furious,movie,http://www.thefastandthefurious.com/,"Gary Scott Thompson (characters), Michael Bran...",2003,tt0322259,5.9,"234,922"
235,"Brad Pitt, Angelina Jolie, Vince Vaughn, Adam ...",9 wins & 18 nominations.,"$186,200,000",USA,29 Nov 2005,Doug Liman,"Action, Comedy, Crime, Thriller","English, Spanish",55,John and Jane Smith are a normal married coupl...,...,True,120 min,Mr. & Mrs. Smith,movie,http://www.mrandmrssmithmovie.com/,Simon Kinberg,2005,tt0356910,6.5,"421,513"
236,"Will Smith, Bill Pullman, Jeff Goldblum, Mary ...",Won 1 Oscar. Another 34 wins & 34 nominations.,N/A,USA,27 Jun 2000,Roland Emmerich,"Action, Adventure, Sci-Fi",English,59,"On July 2nd, communications systems worldwide ...",...,True,145 min,Independence Day,movie,http://www.foxhome.com/id4dvd/html/index_flash...,"Dean Devlin, Roland Emmerich",1996,tt0116629,7.0,"500,076"
237,"Emily Blunt, John Krasinski, Millicent Simmond...",N/A,N/A,USA,10 Jul 2018,John Krasinski,"Drama, Horror, Sci-Fi","English, American Sign Language",82,"In a post-apocalyptic world, a family is force...",...,True,90 min,A Quiet Place,movie,https://www.facebook.com/AQuietPlaceMovie,"Bryan Woods (screenplay by), Scott Beck (scree...",2018,tt6644200,7.5,"319,499"
238,"Alec Baldwin, Steve Buscemi, Jimmy Kimmel, Lis...",Nominated for 1 Oscar. Another 1 win & 19 nomi...,"$174,996,080",USA,25 Jul 2017,Tom McGrath,"Animation, Adventure, Comedy, Family, Fantasy","English, Spanish",50,Seven-year-old Tim Templeton has always been a...,...,True,97 min,The Boss Baby,movie,http://www.dreamworksanimation.com/the-boss-baby/,"Michael McCullers, Marla Frazee (based on the ...",2017,tt3874544,6.3,"95,726"